# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 찰스 by nick
title: 백엔드 어플리케이션 개발 및 셋업 with java, Python
email: heeplay@gmail.com
website: heejun11.github.io/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  python, php, java 기반의 백앤드 개발자이며 약 100Gbps의 CDN(컨텐츠 딜리버리 네트웍) 트래픽을 처리한 경험이 있습니다. Java기반의 오픈소스를 활용한 서비스노드개발과 백앤드 어플을 중점적으로 개발했으며
  약 100만 사용자 API call을 감당하는 아키텍처를 설계, 개발, 운용 경험이 있습니다. 즉, WEB API, 백앤드어플개발, 캐시, 분산DB 구성등 리더로 참여 하였습니다.
  
  또한 1000여대 가량의 서버를 관리한 경험이 있으며, AWS와 자체 IDC등 다양한 형태의 인프라 구성 경험이 있습니다.
  대량 트래픽에 대한 MySQL 분산경험과 서비스 노드 분산 경험이 있습니다.
  
  현재는 좀더 다양한 분야의 경험을 하고자 휴식과 탐색중입니다.
  앞으로 팀단위의 Reader보다는 coder의 역활을 하고자 합니다.   

  # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 에스피소프트
        link: www.spsoft.co.kr
        # link_text: boringcompany.com
        sub_title: 개발 총괄 리더
        caption: 2010.09 - 2022.04
        quote: >
          약 100Gbps CDN 트래픽 서비스 ,누적 500만 사용자 API call 
        description: | # this will include new lines to allow paragraphs
            - 분산 MySQL과 서비스 노드 어플리케이션 개발

              with java, python, php, springboot, redis 캐시, c/c++, go  등

              약 1,000여대 linux Server, 소수 windows Server, 
              
              클라우드 AWS 사용함.( route53, EC2, CloudFront 등)
            - 트래픽 및 모니터링 툴 개발
            - 오픈소스(hadoop)활용 스토리지 서비스구축
            - N/W, 스토리지, server 등 인프라 구축 
            - Media transcode 서비스 구축
            - 운영 자동화와 서비스 개선            

      - layout: left
        title: 애드빌소프트
        link: www.adbillsoft.com
        # link_text: boringcompany.com
        sub_title: 개발
        caption: 2005.06 - 2010.07
        quote: >
            KT IPTV 프로비져닝 서비스 최초 개발 서비스 
        description: | # this will include new lines to allow paragraphs
            - IPTV 프로비져닝 서비스 개발 

              multi thread, daemon, oracle DB, tcp/ip socket,vim, make 등

              고객시스템과 STB, CAS, VOD, 양방향시스템간의 상호작용 및 자동화 처리

              고객 STB 등록, 개통,해지등 자동화 처리( API transaction, format converting, call branch 등)

              컨텐츠 시청,과금 로그 수집 및 정산( Defined formating DATA)

              방송 스케줄링 데이타 수집(XML)

            - IPTV 쿠폰시스템 파일럿 개발(java, oracle)

      - layout: left
        title: 한국소프트웨어써비스
        link: 없음
        # link_text: boringcompany.com
        sub_title: 개발리더
        caption: 1998.09 - 2005.06
        quote: >
            파워콤 통신빌링 시스템 개발 리더 
        description: | # this will include new lines to allow paragraphs
            - 파워콤 통신빌링시스템

              청약, 공정, 요금 계약정보등  매월 과금정산 계산 및 리포트 개발

              요금 어플리케이션 서비스개발 - 요금기준표, 요금처리 

              PowerBuilder, oracle DB, dataMart 연동, SAP ERP 연동, image 데이타 관리

              요금기준표 약 100건, 요금처리 일할계산 등 

              설계 : DB 구조설계, 요금처리 프로세스 설계, 요금기준 설계 등
              DB 파티셔닝설계, DATA관리 등 (튜닝, 데이타백업, 이관 등)

            - 대학학사 정보 시스템

              입시,등록금,수강신청,졸업등 처리

              PowerBuilder, oracle DB 등

              업무분석, DB설계, 기초데이타, 솔류션화 작업


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.


  - title: Skill
    layout: list
    content: 
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - java, python,php, c\c++, go, 
          - Spring Boot, codeIgniter
          - Visual Studio Code

      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - MySQL,MariaDB, Oracle,Mssql
          - MongoDB, Redis, memcached, 
          - S3, EC2, route53, ston, 
          - Apache, Ningx, Tomcat
          - Linux CentOS, Ubunt, RHEL, 
          - mrtg, zabix
          - docker, hadoop,

      - layout: left
        title: Mobile & FrontEnd
        description: | # this will include new lines to allow paragraphs
          - AndroidStuio, react-native, expo, 
          - npm, pip,  
          - html, javascript,Lodash
          - git
          - mssql



  - title: Skill2
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
